### ISSUE TITLE
Wrappers and Interface for fun3dAIM, aflrAIM

### ISSUE THREAD

**Issue by sean-engelstad** [smdogroup/funtofem#124]
* Wrap MPI code that deals with ESP/CAPS fun3dAIM, aflrAIM on serial
* include aim interfaces in funtofem driver and or aero funtofem driver
* auto-registration of funtofem variables through interface to aims for the flow aims (similar to tacs model)
* potentially a fun3d_model class that is registered to the funtofem model?

**Comment by bburke38** [comment]
<img width="1043" alt="Directory Structure" src="https://user-images.githubusercontent.com/97243450/228874723-22a0916e-9fa6-4725-893f-200e7b16ba5a.png">
