### ISSUE TITLE
ModuleNotFoundError: No module named 'tacs'

### ISSUE THREAD

**Issue by jfkiviaho** [smdogroup/funtofem#168]
Hi,

I'm getting this error (and a couple others) on when I install FUNtoFEM in a "clean" environment. I recorded my terminal session to show you how I arrived at it, and I've attached it here. It's not exactly pleasant to read, so I'll try and summarize the main points out of it.

1. I cloned the `funtofem` repository.

2. I created a new Python virtual environment and installed `numpy`, `cython`, and `mpi4py` in it.

3. I installed FUNtoFEM using `make` and `make interface`.

4. I tried to run `examples/functionality/stand_alone/cloud.py` and I got the following error. 

```
Traceback (most recent call last):
  File "/home/jank/Packages/funtofem/examples/functionality/stand_alone/cloud.py", line 76, in <module>
    aero_loads = np.zeros(3 * aero_nnodes, dtype=TransferScheme.dtype)
TypeError: expected a sequence of integers or a single integer, got '12.0'
```

I ran this example really just to see if this bug was still here. It appeared as a consequence of the [division operator changing from Python 2 to Python 3](https://peps.python.org/pep-0238/). This example isn't important, and I imagine the other division operator-related `TypeError` bugs have been caught by now. But I thought I would call it out.

5. I created a barebones example to try importing the `SolverInterface` class, as I would if I were developing a new interface.

```
from pyfuntofem import SolverInterface

print('Hello, world!')
```

6. I ran that example and got the following error.

```
Traceback (most recent call last):
  File "/home/jank/Packages/funtofem/examples/test_interface_import.py", line 1, in <module>
    from pyfuntofem import SolverInterface
  File "/home/jank/Packages/funtofem/pyfuntofem/__init__.py", line 30, in <module>
    from .driver import *
  File "/home/jank/Packages/funtofem/pyfuntofem/driver/__init__.py", line 10, in <module>
    tacs_loader = importlib.util.find_spec("tacs")
AttributeError: module 'importlib' has no attribute 'util'
```

I first encountered this a couple of weeks ago. I found that, according to [this post](https://stackoverflow.com/a/39661116), it's a peculiarity of `importlib` that the `util` module may or may not load as you expect on some systems. I just changed `import importlib` to `import importlib.util` to make sure the `util` module gets loaded. It may just be the Docker container I'm running it on, which is why I didn't mention it sooner. But I thought I might as well now.

7. After applying that fix, I ran the example again and finally got the error I was originally looking for.

```
Traceback (most recent call last):
  File "/home/jank/Packages/funtofem/examples/test_interface_import.py", line 1, in <module>
    from pyfuntofem import SolverInterface
  File "/home/jank/Packages/funtofem/pyfuntofem/__init__.py", line 33, in <modul
e>
    from .interface import *
  File "/home/jank/Packages/funtofem/pyfuntofem/interface/__init__.py", line 31, in <module>
    from .solver_manager import *
  File "/home/jank/Packages/funtofem/pyfuntofem/interface/solver_manager.py", line 5, in <module>
    from .tacs_interface import TacsSteadyInterface
  File "/home/jank/Packages/funtofem/pyfuntofem/interface/tacs_interface.py", line 26, in <module>
    from tacs import pytacs, TACS, functions
ModuleNotFoundError: No module named 'tacs'
```

If I install TACS, the error naturally goes away. And I suppose people installing FUNtoFEM using Conda will never see it. But for the case of a developer who is writing a new solver interface for FUNtoFEM---one that has nothing to do with TACS---this TACS dependency error in FUNtoFEM will be noticeable and will probably seem a little strange. I don't know if this is an issue to be resolved. Maybe the solution is really to insist that FUNtoFEM users, FUNtoFEM developers, and everyone else who can be convinced just install TACS.

--Jan

[reproduce_tacs_module_not_found_error.txt](https://github.com/smdogroup/funtofem/files/11204854/reproduce_tacs_module_not_found_error.txt)

**Comment by sean-engelstad** [comment]
Ah, thanks for pointing out this error. There's not supposed to be an import of a TACS interface class without a `tacs_loader` import check. I tried to make the imports through `__init__.py` in each folder of pyfuntofem agnostic to any particular solver, but it seems that I missed a spot. I'll go through and fix it. 

For example, the `tacs_interface` file isn't imported into the `__init__.py` file of the `pyfuntofem/interface` folder when TACS is not available. However, right now it is incorrectly attempting to import it through the `solver_manager`.
```
# TACS interface, with python package "tacs"
tacs_loader = importlib.util.find_spec("tacs")
if tacs_loader is not None:
    from .tacs_interface import *
    from .tacs_interface_unsteady import *
```

**Comment by sean-engelstad** [comment]
Could you try making the changes in this PR, and make sure it works on your end? I was able to uninstall TACS on my side and fix the imports to install `pyfuntofem`. The PR link is [Agnostic Tacs Import Bug PR](https://github.com/smdogroup/funtofem/pull/170).

**Comment by jfkiviaho** [comment]
Probably not good etiquette to bump this after the PR is merged and the Issue is closed. But I tested the changes on my end and---other than the `importlib` issue I mentioned above, which I think is system-dependent---they resolved the `ModuleNotFoundError` for me. Thanks!
