### ISSUE TITLE
Build error: 'TransferScheme.pxd' not found

### ISSUE THREAD

**Issue by nwukie** [smdogroup/funtofem#195]
A build error/issue seems to have been introduced during some reorganization of the project in commit e256b5f. At that commit, I'm encountering the following error running 'make interface':

```
  Error compiling Cython file:
  ------------------------------------------------------------
  ...

  cdef extern from "mpi-compat.h":
         pass

  # Import the declarations required from the pxd file
  from TransferScheme cimport *
  ^
  ------------------------------------------------------------

  funtofem/TransferScheme.pyx:14:0: 'TransferScheme.pxd' not found
```

The following post seems relevant, particularly since the issue popped up around some reorganization:
https://stackoverflow.com/questions/35512157/error-compiling-cython-file-pxd-not-found-in-package

Not quite clear why it's popping up for us and not the main developers. We are not installing via conda. Commit 1329ed5 builds OK.

**Comment by sean-engelstad** [comment]
I believe this has been fixed now by @A-CGray and @timryanb
