### ISSUE TITLE
Unused variables in Makefile.in.info

### ISSUE THREAD

**Issue by nwukie** [smdogroup/funtofem#2]
It seems like there are some variables in the Makefile.in.info that aren't being used. At least grep-ing for them across the project doesn't turn up any other uses.

PYTHON_INCLUDE
PYTHON_LIB
NUMPY_DIR
MPI4PY_DIR
F2F_LIB
F2F_LD_FLAGS

Consider removing if no longer necessary?

**Comment by gjkennedy** [comment]
I think that the F2F_LIB and F2F_LD_FLAGS are used in linking, and should be referenced elsewhere. The remainder should be removed.

**Comment by LHalim** [comment]
I've just removed those variables and committed the updated Makefile.in.info.
